// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import AsyncStorage from '@react-native-async-storage/async-storage'; // Импорт AsyncStorage
 
const SUPABASE_URL = "https://wdrlhevvavvaleasekge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkcmxoZXZ2YXZ2YWxlYXNla2dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDg2NDQsImV4cCI6MjA3MzE4NDY0NH0.Vf3QLrmJBMMsljOo0Xknxe-4YaKtSGd9Xr88iIn9gGo";
 
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
 
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: AsyncStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});